// Sample DashboardPayload mirroring backend/pipeline/sample_payload.py
// (US-vs-Germany). Used as the /dashboard fallback when no live payload is in
// router state, and as the fixture for chart component tests. NOT live data.

import type { DashboardPayload } from '../types'

// Sample FX (LCU per USD), mirroring backend/pipeline/sample_payload.py.
const US_XR = 1.0
const DE_XR = 0.9239
const netUsd = (netLocal: number, xr: number) => Math.round((netLocal / xr) * 100) / 100

export const sampleDashboard: DashboardPayload = {
  bundle_a: {
    country: 'US',
    wage: {
      gross_annual_local: 132270,
      currency: 'USD',
      source: 'BLS',
      soc_code: '15-1252',
      precision_note: 'Occupation-level US wage (BLS OEWS) for SOC 15-1252.',
    },
    col: {
      city: 'New York',
      col_index: 100,
      exchange_rate_to_usd: US_XR,
      monthly_cost_usd: null,
      source: 'Numbeo',
      col_source: 'city',
      is_fallback: false,
      precision_note: null,
    },
    tax: {
      effective_rate: 0.2638,
      net_annual_local: 97364,
      notes: 'Federal income tax + FICA; state taxes not included.',
    },
    net_annual_usd: netUsd(97364, US_XR),
    visa_route: {
      visa_slug: 'us_h1b',
      visa_name: 'H-1B Specialty Occupation',
      eligibility_summary: "Bachelor's+ in a specialty field with a sponsoring employer.",
      employer_sponsorship_required: true,
      path_to_residency_years: 6,
      key_constraint: 'Annual lottery cap; selection is not guaranteed.',
      routing_confidence: 'high',
      source_url: 'https://www.uscis.gov/working-in-the-united-states/h-1b-specialty-occupations',
      source_retrieved: '2026-06-19',
    },
    visa_enrichment: {
      min_salary: 60000,
      currency: 'USD',
      can_switch_employer: true,
      switch_conditions: 'New employer must file a fresh H-1B petition (no re-lottery).',
      lottery_required: true,
      lottery_annual_rate: 0.14,
      lottery_history: [{ year: 2024, rate: 0.14 }],
      lottery_cumulative_3yr: 0.3639,
      partner_work_rights: 'restricted',
      partner_work_notes: 'H-4 dependents need an EAD; eligible only in limited cases.',
      last_verified: '2026-06-19',
      curated_source_url:
        'https://www.uscis.gov/working-in-the-united-states/h-1b-specialty-occupations',
    },
  },
  bundle_b: {
    country: 'Germany',
    wage: {
      gross_annual_local: 54000,
      currency: 'EUR',
      source: 'OECD',
      soc_code: null,
      precision_note: 'National-average wage (OECD); not occupation-specific.',
    },
    col: {
      city: 'Berlin',
      col_index: 65.3,
      exchange_rate_to_usd: DE_XR,
      monthly_cost_usd: null,
      source: 'Numbeo',
      col_source: 'city',
      is_fallback: false,
      precision_note: null,
    },
    tax: {
      effective_rate: 0.3168,
      net_annual_local: 36895,
      notes: 'Income tax + approximate employee social contributions.',
    },
    net_annual_usd: netUsd(36895, DE_XR),
    visa_route: {
      visa_slug: 'de_eu_blue_card',
      visa_name: 'EU Blue Card (Germany)',
      eligibility_summary: 'Recognised degree + a job offer above the salary threshold.',
      employer_sponsorship_required: false,
      path_to_residency_years: 4,
      key_constraint: 'Salary must meet the annual Blue Card threshold.',
      routing_confidence: 'medium',
      source_url: 'https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card',
      source_retrieved: '2026-06-19',
    },
    visa_enrichment: {
      min_salary: 45300,
      currency: 'EUR',
      can_switch_employer: true,
      switch_conditions: 'Employer change in the first 12 months needs authority approval.',
      lottery_required: false,
      lottery_annual_rate: null,
      lottery_history: [],
      lottery_cumulative_3yr: null,
      partner_work_rights: 'full',
      partner_work_notes: 'Spouse gets unrestricted labour-market access.',
      last_verified: '2026-06-19',
      curated_source_url: 'https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card',
    },
  },
  outlook_a: {
    trend_summary: 'US immigration policy has been broadly stable over the past year.',
    trend_direction: 'stable',
    key_recent_change: 'No major statutory change in the last 12 months.',
    career_context: 'Demand for skilled technical workers remains strong.',
    source_url: 'https://example.gov/immigration-outlook',
    source_publish_date: '2026-05-01',
    confidence: 'medium',
  },
  outlook_b: {
    trend_summary: 'Germany immigration policy has been broadly stable over the past year.',
    trend_direction: 'stable',
    key_recent_change: 'No major statutory change in the last 12 months.',
    career_context: 'Demand for skilled technical workers remains strong.',
    source_url: 'https://example.gov/immigration-outlook',
    source_publish_date: '2026-05-01',
    confidence: 'medium',
  },
  insights: [
    {
      type: 'insight',
      scenario_type: 'base',
      fact_used: 'bundle_a.net_annual_usd',
      context_used: 'long-term residency stability',
      connection: 'take-home and residency both depend on holding the visa',
      consideration:
        'The higher US take-home is contingent on clearing the H-1B lottery, so the nominal gap overstates the guaranteed advantage.',
      confidence: 'high',
      confidence_basis: 'Lottery rate and wage are both curated facts.',
      next_action: 'Compare your offer salary against the H-1B prevailing-wage floor.',
    },
    {
      type: 'safe_fallback',
      reason: 'Generated insight failed validation (fact_used did not match a real fact key).',
      slot_index: 5,
    },
  ],
  sacrifice_map: {
    net_takehome_usd: {
      dimension: 'net_takehome_usd',
      country_a_value: netUsd(97364, US_XR),
      country_b_value: netUsd(36895, DE_XR),
      delta: Math.round((netUsd(97364, US_XR) - netUsd(36895, DE_XR)) * 100) / 100,
      winner: 'a',
      note: 'Annual take-home converted to USD (nominal, market FX).',
    },
    col_relative: {
      dimension: 'col_relative',
      country_a_value: 100,
      country_b_value: 65.3,
      delta: -34.7,
      winner: 'b',
      note: 'Cost of living relative to Country A (A = 100; lower is cheaper).',
    },
    visa_stability_score: {
      dimension: 'visa_stability_score',
      country_a_value: 0.36,
      country_b_value: 0.9,
      delta: -0.54,
      winner: 'b',
      note: "Germany's no-lottery route is far more certain.",
    },
    pr_timeline_years: {
      dimension: 'pr_timeline_years',
      country_a_value: 6,
      country_b_value: 4,
      delta: 2,
      winner: 'b',
      note: 'Germany reaches permanent residency sooner.',
    },
    lottery_risk: {
      dimension: 'lottery_risk',
      country_a_value: 0.64,
      country_b_value: 0,
      delta: 0.64,
      winner: 'b',
      note: 'US H-1B carries a ~64% three-year non-selection risk.',
    },
    partner_opportunity: {
      dimension: 'partner_opportunity',
      country_a_value: 'restricted',
      country_b_value: 'full',
      delta: null,
      winner: 'b',
      note: 'Germany grants full partner work rights.',
    },
  },
  pipeline_meta: {
    ai_calls_made: 2,
    insights_passed: 1,
    insights_withheld: 1,
    routing_confidence_a: 'high',
    routing_confidence_b: 'medium',
    fact_sources: {
      wage: 'BLS / OECD',
      cost_of_living: 'Numbeo (mock)',
      tax: 'curated tax_rates.json',
      visa: 'curated visa_rules.json',
      note: 'SAMPLE / stub payload — not live data',
    },
  },
}
